# Generated by Django 5.0.3 on 2024-04-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercise', '0002_alter_courseexcercise_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerciseresult',
            name='excercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excercise_result', to='excercise.courseexcercise'),
        ),
    ]
