# Generated by Django 5.0.3 on 2024-04-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercise', '0003_alter_excerciseresult_excercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexcercise',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=125, unique=True),
        ),
    ]
