# Generated by Django 5.0.3 on 2024-03-09 11:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PY', 'Python'), ('RS', 'Rust'), ('JV', 'Java'), ('JS', 'JavaScript'), ('CS', 'C#'), ('CPP', 'C++'), ('HTSS', 'HTML/CSS'), ('REA', 'React'), ('ANG', 'Angular'), ('VUE', 'Vue.js'), ('PHP', 'PHP'), ('SW', 'Swift'), ('KT', 'Kotlin'), ('GO', 'Go'), ('RB', 'Ruby'), ('SQL', 'SQL'), ('ML', 'Machine Learning'), ('DS', 'Data Science'), ('DSA', 'Data Structure and Algorithm'), ('AI', 'Artificial Intelligence'), ('BC', 'Blockchain'), ('DO', 'DevOps'), ('CC', 'Cloud Computing'), ('BE', 'Backend Development'), ('FE', 'Frontend Development'), ('GAME', 'Game Development'), ('MOB', 'Mobile App Development'), ('WEB', 'Web Development'), ('UIUX', 'UI/UX Design'), ('DB', 'Databases'), ('SEC', 'Cyber Security')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('youtube', models.URLField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('is_free', models.BooleanField()),
                ('categories', models.ManyToManyField(to='courses.coursecategory')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('pointer', models.TextField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
