# Generated by Django 5.0.3 on 2024-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursesection_pointer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='courseprice',
            name='paid_type',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Paid')], default='F', max_length=1),
        ),
    ]
