# Generated by Django 5.0.3 on 2024-03-09 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_is_free_courseprice_paid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
