# Generated by Django 5.0.3 on 2024-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_usercourse_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='completed_section',
            field=models.ManyToManyField(blank=True, to='courses.coursesection'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('course', 'section')},
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='completion',
        ),
    ]
