# Generated by Django 5.0.3 on 2024-03-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_coursesection_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='completed_section',
        ),
    ]
